<a href="https://colab.research.google.com/github/Arigalan/Pr-ctica_Limpieza_Happiness_Score/blob/main/Pr%C3%A1ctica_Limpieza_Happiness_Score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Práctica

In [ ]:
import pandas as pd
df = pd.read_csv("world_happiness_report_2005_2025.csv")
df

,year,rank_in_year,country,happiness_score,lower_whisker,upper_whisker,explained_log_gdp_per_capita,explained_social_support,explained_healthy_life_expectancy,explained_freedom,explained_generosity,explained_corruption,dystopia_plus_residual
0,2011,1,Denmark,7.856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,2,Finland,7.579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,3,Norway,7.524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,4,Netherlands,7.512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,5,Canada,7.499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,2025,143,Botswana,3.464,3.335,3.593,1.582,0.989,0.017,0.860,0.022,0.093,-0.099
2112,2025,144,Zimbabwe,3.346,3.244,3.449,1.213,0.782,0.189,0.729,0.056,0.128,0.251
2113,2025,145,Malawi,3.284,3.153,3.415,0.864,0.326,0.299,0.812,0.109,0.143,0.730
2114,2025,146,Sierra Leone,3.251,3.147,3.355,1.054,0.692,0.405,0.800,0.131,0.052,0.117
2115,2025,147,Afghanistan,1.446,1.348,1.544,0.921,0.000,0.176,0.000,0.079,0.131,0.139

Paso 2: Exploración Inicial

In [ ]:
print("La cantidad de columnas del dataset son: ", len(df.columns))
print("Las variables que contiene son: ", df.columns)

La cantidad de columnas del dataset son:  13
Las variables que contiene son:  Index(['year', 'rank_in_year', 'country', 'happiness_score', 'lower_whisker',
       'upper_whisker', 'explained_log_gdp_per_capita',
       'explained_social_support', 'explained_healthy_life_expectancy',
       'explained_freedom', 'explained_generosity', 'explained_corruption',
       'dystopia_plus_residual'],
      dtype='object')

Paso 3: Detectar valores nulos

In [ ]:
df.isnull().sum()

year                                    0
rank_in_year                            0
country                                 0
happiness_score                         0
lower_whisker                        1094
upper_whisker                        1094
explained_log_gdp_per_capita         1097
explained_social_support             1097
explained_healthy_life_expectancy    1100
explained_freedom                    1099
explained_generosity                 1097
explained_corruption                 1098
dystopia_plus_residual               1103
dtype: int64

In [ ]:
df_columnas_nulas = df.copy()

In [ ]:
df_columnas_nulas = df[[
    "lower_whisker",
    "upper_whisker",
    "explained_log_gdp_per_capita",
    "explained_social_support",
    "explained_healthy_life_expectancy",
    "explained_freedom",
    "explained_generosity",
    "explained_corruption",
    "dystopia_plus_residual"
]]

print("Las columnas que tienen valores nulos son: ")
df_columnas_nulas.columns

Las columnas que tienen valores nulos son:

Index(['lower_whisker', 'upper_whisker', 'explained_log_gdp_per_capita',
       'explained_social_support', 'explained_healthy_life_expectancy',
       'explained_freedom', 'explained_generosity', 'explained_corruption',
       'dystopia_plus_residual'],
      dtype='object')

In [ ]:
print("La columna que tiene más valores faltantes es: ", df.isnull().sum().idxmax())

La columna que tiene más valores faltantes es:  dystopia_plus_residual

Paso 4: Limpieza de datos

Eliminar espacios en blanco en la columna "Country"

In [ ]:
df["country"]= df["country"].str.strip()
df

,year,rank_in_year,country,happiness_score,lower_whisker,upper_whisker,explained_log_gdp_per_capita,explained_social_support,explained_healthy_life_expectancy,explained_freedom,explained_generosity,explained_corruption,dystopia_plus_residual
0,2011,1,Denmark,7.856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,2,Finland,7.579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,3,Norway,7.524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,4,Netherlands,7.512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,5,Canada,7.499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,2025,143,Botswana,3.464,3.335,3.593,1.582,0.989,0.017,0.860,0.022,0.093,-0.099
2112,2025,144,Zimbabwe,3.346,3.244,3.449,1.213,0.782,0.189,0.729,0.056,0.128,0.251
2113,2025,145,Malawi,3.284,3.153,3.415,0.864,0.326,0.299,0.812,0.109,0.143,0.730
2114,2025,146,Sierra Leone,3.251,3.147,3.355,1.054,0.692,0.405,0.800,0.131,0.052,0.117
2115,2025,147,Afghanistan,1.446,1.348,1.544,0.921,0.000,0.176,0.000,0.079,0.131,0.139

Convertir los nombre a formato correcto en la columna "country"

Pregunta: ¿Por qué es importante limpiar los nombres de texto antes de analizar?

R: Pienso que es importante para que todos estén en el mismo formato y no haya errores al aplicar ciertos filtros o algún sesgo de los datos

In [ ]:
df["country"] = df["country"].str.capitalize()
df

,year,rank_in_year,country,happiness_score,lower_whisker,upper_whisker,explained_log_gdp_per_capita,explained_social_support,explained_healthy_life_expectancy,explained_freedom,explained_generosity,explained_corruption,dystopia_plus_residual
0,2011,1,Denmark,7.856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,2,Finland,7.579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,3,Norway,7.524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,4,Netherlands,7.512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,5,Canada,7.499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,2025,143,Botswana,3.464,3.335,3.593,1.582,0.989,0.017,0.860,0.022,0.093,-0.099
2112,2025,144,Zimbabwe,3.346,3.244,3.449,1.213,0.782,0.189,0.729,0.056,0.128,0.251
2113,2025,145,Malawi,3.284,3.153,3.415,0.864,0.326,0.299,0.812,0.109,0.143,0.730
2114,2025,146,Sierra leone,3.251,3.147,3.355,1.054,0.692,0.405,0.800,0.131,0.052,0.117
2115,2025,147,Afghanistan,1.446,1.348,1.544,0.921,0.000,0.176,0.000,0.079,0.131,0.139

Paso 5: Selección de variables

In [ ]:
df_columnas_seleccionadas = df[["country", "year", "happiness_score"]]
df_columnas_seleccionadas

           country  year  happiness_score
0          Denmark  2011            7.856
1          Finland  2011            7.579
2           Norway  2011            7.524
3      Netherlands  2011            7.512
4           Canada  2011            7.499
...            ...   ...              ...
2111      Botswana  2025            3.464
2112      Zimbabwe  2025            3.346
2113        Malawi  2025            3.284
2114  Sierra leone  2025            3.251
2115   Afghanistan  2025            1.446

[2116 rows x 3 columns]

Paso 6: Rellenar con media

In [ ]:
df["happiness_score"] = df["happiness_score"].fillna(df["happiness_score"].mean())
df

,year,rank_in_year,country,happiness_score,lower_whisker,upper_whisker,explained_log_gdp_per_capita,explained_social_support,explained_healthy_life_expectancy,explained_freedom,explained_generosity,explained_corruption,dystopia_plus_residual
0,2011,1,Denmark,7.856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,2,Finland,7.579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,3,Norway,7.524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,4,Netherlands,7.512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,5,Canada,7.499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,2025,143,Botswana,3.464,3.335,3.593,1.582,0.989,0.017,0.860,0.022,0.093,-0.099
2112,2025,144,Zimbabwe,3.346,3.244,3.449,1.213,0.782,0.189,0.729,0.056,0.128,0.251
2113,2025,145,Malawi,3.284,3.153,3.415,0.864,0.326,0.299,0.812,0.109,0.143,0.730
2114,2025,146,Sierra leone,3.251,3.147,3.355,1.054,0.692,0.405,0.800,0.131,0.052,0.117
2115,2025,147,Afghanistan,1.446,1.348,1.544,0.921,0.000,0.176,0.000,0.079,0.131,0.139

¿Este método representa bien los datos?

R: Podemos ver que si es la más adecuada, debido a que los datos van escalando, por lo cual no hay valores outliers o muy alejados de la media, por lo cual ¿, no convendría usar la mediana. Ahora, como hay valores repetidos casi la misma cantidad de veces, pues no conviene usar la moda porque eso no representa a los datos

Paso 7: Rellenar con mediana

In [ ]:
df["happiness_score"] = df["happiness_score"].fillna(df["happiness_score"].median())
df

,year,rank_in_year,country,happiness_score,lower_whisker,upper_whisker,explained_log_gdp_per_capita,explained_social_support,explained_healthy_life_expectancy,explained_freedom,explained_generosity,explained_corruption,dystopia_plus_residual
0,2011,1,Denmark,7.856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,2,Finland,7.579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,3,Norway,7.524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,4,Netherlands,7.512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,5,Canada,7.499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,2025,143,Botswana,3.464,3.335,3.593,1.582,0.989,0.017,0.860,0.022,0.093,-0.099
2112,2025,144,Zimbabwe,3.346,3.244,3.449,1.213,0.782,0.189,0.729,0.056,0.128,0.251
2113,2025,145,Malawi,3.284,3.153,3.415,0.864,0.326,0.299,0.812,0.109,0.143,0.730
2114,2025,146,Sierra leone,3.251,3.147,3.355,1.054,0.692,0.405,0.800,0.131,0.052,0.117
2115,2025,147,Afghanistan,1.446,1.348,1.544,0.921,0.000,0.176,0.000,0.079,0.131,0.139

¿Cuál método parece más adecuado?

R: Me parece más adecuado el de la media

Paso 8: Comparación

In [ ]:
print("La media es: ", df['happiness_score'].mean())
print("La mediana es: ", df['happiness_score'].median())

La media es:  5.465654867209829
La mediana es:  5.48

¿Hay diferencias entre media y mediana?

R: No hay mucha diferencia

In [ ]:
df.describe()

,year,rank_in_year,happiness_score,lower_whisker,upper_whisker,explained_log_gdp_per_capita,explained_social_support,explained_healthy_life_expectancy,explained_freedom,explained_generosity,explained_corruption,dystopia_plus_residual
count,2116.000000,2116.000000,2116.000000,1022.000000,1022.000000,1019.000000,1019.000000,1016.000000,1017.000000,1019.000000,1018.000000,1013.000000
mean,2018.220227,76.190926,5.465655,5.436091,5.664733,1.265670,1.096746,0.553435,0.609465,0.147343,0.144911,1.736935
std,4.249844,43.845101,1.123870,1.140959,1.107424,0.463823,0.357642,0.229980,0.212070,0.084335,0.118803,0.657497
min,2011.000000,1.000000,1.364000,1.301000,1.427000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.295000
25%,2015.000000,38.000000,4.604750,4.619707,4.867750,0.944000,0.865000,0.389750,0.471000,0.088000,0.063156,1.305000
50%,2018.000000,76.000000,5.480000,5.592631,5.812000,1.304000,1.140119,0.560500,0.602000,0.134000,0.113000,1.765000
75%,2022.000000,114.000000,6.321250,6.290110,6.486500,1.636000,1.382000,0.712325,0.735000,0.195477,0.181330,2.178000
max,2025.000000,158.000000,7.856000,7.780000,7.904000,2.209000,1.840000,1.238000,1.147000,0.569814,0.587000,3.482000

¿Existen valores extremos (outliers)?

Al parecer con el describe() puedo ver que no hay outliers, por lo cual, la media sigue siendo la mejor opción a considerar porque representa bien a los datos

Paso 9

¿Qué método elegirías y por qué?

R: Seguiría eligiendo rellenar los datos con la media porque al final es el método que mejor representa a los datos

¿Los valores nulos afectan el análisis?

R: Si no los rellenamos con ninún dato extra, como lo puede ser la media, puede ser que sí afecte al resultado final

¿La limpieza de texto influye en los resultados?

R: Sí, porque de ésta manera los datos se encuentran más organizados y podemos filtrarlos o trabajar con ellos de mejor manera